name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build one-file binaries
        run: |
          bash build-linux.sh

      - name: Package artifacts
        run: |
          set -euxo pipefail
          mkdir -p release
          cp dist/karel-switcher release/
          tar -czf release/karel-switcher-linux-x86_64.tar.gz -C release karel-switcher
          rm -f release/karel-switcher
          cp dist/karel-switcher-mpv release/
          tar -czf release/karel-switcher-mpv-linux-x86_64.tar.gz -C release karel-switcher-mpv
          rm -f release/karel-switcher-mpv
          cp README.md config.sample.json release/
          (cd release && sha256sum *.tar.gz > SHA256SUMS)

      - name: Upload artifacts (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            release/karel-switcher-linux-x86_64.tar.gz
            release/karel-switcher-mpv-linux-x86_64.tar.gz
            release/SHA256SUMS
            release/README.md
            release/config.sample.json

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build app bundle and onefile
        run: |
          bash build-mac.sh

      - name: Package artifacts
        run: |
          set -euxo pipefail
          mkdir -p release
          cd dist
          ditto -c -k --sequesterRsrc --keepParent KarelSwitcher.app ../release/KarelSwitcher-macOS.app.zip
          tar -czf ../release/karel-switcher-macOS-$(uname -m).tar.gz karel-switcher
          tar -czf ../release/karel-switcher-mpv-macOS-$(uname -m).tar.gz karel-switcher-mpv
          cd ../release
          shasum -a 256 KarelSwitcher-macOS.app.zip karel-switcher-macOS-*.tar.gz karel-switcher-mpv-macOS-*.tar.gz > SHA256SUMS

      - name: Upload artifacts (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            release/KarelSwitcher-macOS.app.zip
            release/SHA256SUMS
            release/karel-switcher-macOS-*.tar.gz
            release/karel-switcher-mpv-macOS-*.tar.gz

  release:
    name: Create GitHub Release
    needs: [build-linux, build-macos]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-artifacts
          path: release/linux

      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-artifacts
          path: release/macos

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/linux/karel-switcher-linux-x86_64.tar.gz
            release/linux/karel-switcher-mpv-linux-x86_64.tar.gz
            release/linux/SHA256SUMS
            release/linux/README.md
            release/linux/config.sample.json
            release/macos/KarelSwitcher-macOS.app.zip
            release/macos/SHA256SUMS
            release/macos/karel-switcher-macOS-*.tar.gz
            release/macos/karel-switcher-mpv-macOS-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
